name: Build
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          # - macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v3
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
          restore-keys: |
            ${{ runner.os }}-nimble-
        if: runner.os != 'Windows'
      - name: Setup nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: "2.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: nimble build -Y
