name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run-nix:
    name: Run Nix development shell
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Cache Nimble
        id: cache-nimble
        uses: actions/cache@v3
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
          restore-keys: |
            ${{ runner.os }}-nimble-
      - name: Enter Nix development shell
        run: nix develop
      - name: Run `nimble build -Y`
        run: nimble build -Y
